export const COUNTRY_OPTIONS = [
  { name: 'Afghanistan', dialCode: '93', code: 'AF', flag: '🇦🇫', minLength: 9, maxLength: 9 },
  { name: 'Albania', dialCode: '355', code: 'AL', flag: '🇦🇱', minLength: 9, maxLength: 9 },
  { name: 'Algeria', dialCode: '213', code: 'DZ', flag: '🇩🇿', minLength: 9, maxLength: 9 },
  { name: 'American Samoa', dialCode: '1684', code: 'AS', flag: '🇦🇸', minLength: 10, maxLength: 10 },
  { name: 'Andorra', dialCode: '376', code: 'AD', flag: '🇦🇩', minLength: 9, maxLength: 9 },
  { name: 'Angola', dialCode: '244', code: 'AO', flag: '🇦🇴', minLength: 9, maxLength: 9 },
  { name: 'Anguilla', dialCode: '1264', code: 'AI', flag: '🇦🇮', minLength: 10, maxLength: 10 },
  { name: 'Antigua and Barbuda', dialCode: '1268', code: 'AG', flag: '🇦🇬', minLength: 10, maxLength: 10 },
  { name: 'Argentina', dialCode: '54', code: 'AR', flag: '🇦🇷', minLength: 10, maxLength: 10 },
  { name: 'Armenia', dialCode: '374', code: 'AM', flag: '🇦🇲', minLength: 8, maxLength: 8 },
  { name: 'Aruba', dialCode: '297', code: 'AW', flag: '🇦🇼', minLength: 7, maxLength: 7 },
  { name: 'Australia', dialCode: '61', code: 'AU', flag: '🇦🇺', minLength: 9, maxLength: 9 },
  { name: 'Austria', dialCode: '43', code: 'AT', flag: '🇦🇹', minLength: 10, maxLength: 13 },
  { name: 'Azerbaijan', dialCode: '994', code: 'AZ', flag: '🇦🇿', minLength: 9, maxLength: 9 },
  { name: 'Bahamas', dialCode: '1242', code: 'BS', flag: '🇧🇸', minLength: 10, maxLength: 10 },
  { name: 'Bahrain', dialCode: '973', code: 'BH', flag: '🇧🇭', minLength: 8, maxLength: 8 },
  { name: 'Bangladesh', dialCode: '880', code: 'BD', flag: '🇧🇩', minLength: 10, maxLength: 10 },
  { name: 'Barbados', dialCode: '1246', code: 'BB', flag: '🇧🇧', minLength: 10, maxLength: 10 },
  { name: 'Belarus', dialCode: '375', code: 'BY', flag: '🇧🇾', minLength: 9, maxLength: 9 },
  { name: 'Belgium', dialCode: '32', code: 'BE', flag: '🇧🇪', minLength: 9, maxLength: 9 },
  { name: 'Belize', dialCode: '501', code: 'BZ', flag: '🇧🇿', minLength: 7, maxLength: 7 },
  { name: 'Benin', dialCode: '229', code: 'BJ', flag: '🇧🇯', minLength: 8, maxLength: 8 },
  { name: 'Bermuda', dialCode: '1441', code: 'BM', flag: '🇧🇲', minLength: 10, maxLength: 10 },
  { name: 'Bhutan', dialCode: '975', code: 'BT', flag: '🇧🇹', minLength: 8, maxLength: 8 },
  { name: 'Bolivia', dialCode: '591', code: 'BO', flag: '🇧🇴', minLength: 8, maxLength: 8 },
  { name: 'Bosnia and Herzegovina', dialCode: '387', code: 'BA', flag: '🇧🇦', minLength: 8, maxLength: 8 },
  { name: 'Botswana', dialCode: '267', code: 'BW', flag: '🇧🇼', minLength: 8, maxLength: 8 },
  { name: 'Brazil', dialCode: '55', code: 'BR', flag: '🇧🇷', minLength: 10, maxLength: 11 },
  { name: 'British Indian Ocean Territory', dialCode: '246', code: 'IO', flag: '🇮🇴', minLength: 7, maxLength: 7 },
  { name: 'British Virgin Islands', dialCode: '1284', code: 'VG', flag: '🇻🇬', minLength: 10, maxLength: 10 },
  { name: 'Brunei', dialCode: '673', code: 'BN', flag: '🇧🇳', minLength: 7, maxLength: 7 },
  { name: 'Bulgaria', dialCode: '359', code: 'BG', flag: '🇧🇬', minLength: 8, maxLength: 9 },
  { name: 'Burkina Faso', dialCode: '226', code: 'BF', flag: '🇧🇫', minLength: 8, maxLength: 8 },
  { name: 'Burundi', dialCode: '257', code: 'BI', flag: '🇧🇮', minLength: 8, maxLength: 8 },
  { name: 'Cambodia', dialCode: '855', code: 'KH', flag: '🇰🇭', minLength: 8, maxLength: 9 },
  { name: 'Cameroon', dialCode: '237', code: 'CM', flag: '🇨🇲', minLength: 9, maxLength: 9 },
  { name: 'Canada', dialCode: '1', code: 'CA', flag: '🇨🇦', minLength: 10, maxLength: 10 },
  { name: 'Cape Verde', dialCode: '238', code: 'CV', flag: '🇨🇻', minLength: 7, maxLength: 7 },
  { name: 'Cayman Islands', dialCode: '1345', code: 'KY', flag: '🇰🇾', minLength: 10, maxLength: 10 },
  { name: 'Central African Republic', dialCode: '236', code: 'CF', flag: '🇨🇫', minLength: 8, maxLength: 8 },
  { name: 'Chad', dialCode: '235', code: 'TD', flag: '🇹🇩', minLength: 8, maxLength: 8 },
  { name: 'Chile', dialCode: '56', code: 'CL', flag: '🇨🇱', minLength: 9, maxLength: 9 },
  { name: 'China', dialCode: '86', code: 'CN', flag: '🇨🇳', minLength: 11, maxLength: 11 },
  { name: 'Colombia', dialCode: '57', code: 'CO', flag: '🇨🇴', minLength: 10, maxLength: 10 },
  { name: 'Comoros', dialCode: '269', code: 'KM', flag: '🇰🇲', minLength: 7, maxLength: 7 },
  { name: 'Congo (DRC)', dialCode: '243', code: 'CD', flag: '🇨🇩', minLength: 9, maxLength: 9 },
  { name: 'Congo (Republic)', dialCode: '242', code: 'CG', flag: '🇨🇬', minLength: 9, maxLength: 9 },
  { name: 'Cook Islands', dialCode: '682', code: 'CK', flag: '🇨🇰', minLength: 5, maxLength: 5 },
  { name: 'Costa Rica', dialCode: '506', code: 'CR', flag: '🇨🇷', minLength: 8, maxLength: 8 },
  { name: "Cote d'Ivoire", dialCode: '225', code: 'CI', flag: '🇨🇮', minLength: 8, maxLength: 8 },
  { name: 'Croatia', dialCode: '385', code: 'HR', flag: '🇭🇷', minLength: 9, maxLength: 9 },
  { name: 'Cuba', dialCode: '53', code: 'CU', flag: '🇨🇺', minLength: 8, maxLength: 8 },
  { name: 'Curacao', dialCode: '599', code: 'CW', flag: '🇨🇼', minLength: 7, maxLength: 7 },
  { name: 'Cyprus', dialCode: '357', code: 'CY', flag: '🇨🇾', minLength: 8, maxLength: 8 },
  { name: 'Czech Republic', dialCode: '420', code: 'CZ', flag: '🇨🇿', minLength: 9, maxLength: 9 },
  { name: 'Denmark', dialCode: '45', code: 'DK', flag: '🇩🇰', minLength: 8, maxLength: 8 },
  { name: 'Djibouti', dialCode: '253', code: 'DJ', flag: '🇩🇯', minLength: 8, maxLength: 8 },
  { name: 'Dominica', dialCode: '1767', code: 'DM', flag: '🇩🇲', minLength: 10, maxLength: 10 },
  { name: 'Dominican Republic', dialCode: '1809', code: 'DO', flag: '🇩🇴', minLength: 10, maxLength: 10 },
  { name: 'Ecuador', dialCode: '593', code: 'EC', flag: '🇪🇨', minLength: 9, maxLength: 9 },
  { name: 'Egypt', dialCode: '20', code: 'EG', flag: '🇪🇬', minLength: 10, maxLength: 10 },
  { name: 'El Salvador', dialCode: '503', code: 'SV', flag: '🇸🇻', minLength: 8, maxLength: 8 },
  { name: 'Equatorial Guinea', dialCode: '240', code: 'GQ', flag: '🇬🇶', minLength: 9, maxLength: 9 },
  { name: 'Eritrea', dialCode: '291', code: 'ER', flag: '🇪🇷', minLength: 7, maxLength: 7 },
  { name: 'Estonia', dialCode: '372', code: 'EE', flag: '🇪🇪', minLength: 8, maxLength: 8 },
  { name: 'Eswatini', dialCode: '268', code: 'SZ', flag: '🇸🇿', minLength: 8, maxLength: 8 },
  { name: 'Ethiopia', dialCode: '251', code: 'ET', flag: '🇪🇹', minLength: 9, maxLength: 9 },
  { name: 'Faroe Islands', dialCode: '298', code: 'FO', flag: '🇫🇴', minLength: 8, maxLength: 8 },
  { name: 'Fiji', dialCode: '679', code: 'FJ', flag: '🇫🇯', minLength: 7, maxLength: 7 },
  { name: 'Finland', dialCode: '358', code: 'FI', flag: '🇫🇮', minLength: 10, maxLength: 10 },
  { name: 'France', dialCode: '33', code: 'FR', flag: '🇫🇷', minLength: 9, maxLength: 9 },
  { name: 'French Guiana', dialCode: '594', code: 'GF', flag: '🇬🇫', minLength: 9, maxLength: 9 },
  { name: 'French Polynesia', dialCode: '689', code: 'PF', flag: '🇵🇫', minLength: 8, maxLength: 8 },
  { name: 'Gabon', dialCode: '241', code: 'GA', flag: '🇬🇦', minLength: 8, maxLength: 8 },
  { name: 'Gambia', dialCode: '220', code: 'GM', flag: '🇬🇲', minLength: 7, maxLength: 7 },
  { name: 'Georgia', dialCode: '995', code: 'GE', flag: '🇬🇪', minLength: 9, maxLength: 9 },
  { name: 'Germany', dialCode: '49', code: 'DE', flag: '🇩🇪', minLength: 10, maxLength: 11 },
  { name: 'Ghana', dialCode: '233', code: 'GH', flag: '🇬🇭', minLength: 9, maxLength: 9 },
  { name: 'Gibraltar', dialCode: '350', code: 'GI', flag: '🇬🇮', minLength: 8, maxLength: 8 },
  { name: 'Greece', dialCode: '30', code: 'GR', flag: '🇬🇷', minLength: 10, maxLength: 10 },
  { name: 'Greenland', dialCode: '299', code: 'GL', flag: '🇬🇱', minLength: 6, maxLength: 6 },
  { name: 'Grenada', dialCode: '1473', code: 'GD', flag: '🇬🇩', minLength: 10, maxLength: 10 },
  { name: 'Guadeloupe', dialCode: '590', code: 'GP', flag: '🇬🇵', minLength: 9, maxLength: 9 },
  { name: 'Guam', dialCode: '1671', code: 'GU', flag: '🇬🇺', minLength: 10, maxLength: 10 },
  { name: 'Guatemala', dialCode: '502', code: 'GT', flag: '🇬🇹', minLength: 8, maxLength: 8 },
  { name: 'Guernsey', dialCode: '44', code: 'GG', flag: '🇬🇬', minLength: 10, maxLength: 10 },
  { name: 'Guinea', dialCode: '224', code: 'GN', flag: '🇬🇳', minLength: 9, maxLength: 9 },
  { name: 'Guinea-Bissau', dialCode: '245', code: 'GW', flag: '🇬🇼', minLength: 7, maxLength: 7 },
  { name: 'Guyana', dialCode: '592', code: 'GY', flag: '🇬🇾', minLength: 7, maxLength: 7 },
  { name: 'Haiti', dialCode: '509', code: 'HT', flag: '🇭🇹', minLength: 8, maxLength: 8 },
  { name: 'Honduras', dialCode: '504', code: 'HN', flag: '🇭🇳', minLength: 8, maxLength: 8 },
  { name: 'Hong Kong', dialCode: '852', code: 'HK', flag: '🇭🇰', minLength: 8, maxLength: 8 },
  { name: 'Hungary', dialCode: '36', code: 'HU', flag: '🇭🇺', minLength: 9, maxLength: 9 },
  { name: 'Iceland', dialCode: '354', code: 'IS', flag: '🇮🇸', minLength: 7, maxLength: 7 },
  { name: 'India', dialCode: '91', code: 'IN', flag: '🇮🇳', minLength: 10, maxLength: 10 },
  { name: 'Indonesia', dialCode: '62', code: 'ID', flag: '🇮🇩', minLength: 10, maxLength: 11 },
  { name: 'Iran', dialCode: '98', code: 'IR', flag: '🇮🇷', minLength: 10, maxLength: 10 },
  { name: 'Iraq', dialCode: '964', code: 'IQ', flag: '🇮🇶', minLength: 10, maxLength: 10 },
  { name: 'Ireland', dialCode: '353', code: 'IE', flag: '🇮🇪', minLength: 9, maxLength: 9 },
  { name: 'Isle of Man', dialCode: '44', code: 'IM', flag: '🇮🇲', minLength: 10, maxLength: 10 },
  { name: 'Israel', dialCode: '972', code: 'IL', flag: '🇮🇱', minLength: 9, maxLength: 9 },
  { name: 'Italy', dialCode: '39', code: 'IT', flag: '🇮🇹', minLength: 10, maxLength: 10 },
  { name: 'Jamaica', dialCode: '1876', code: 'JM', flag: '🇯🇲', minLength: 10, maxLength: 10 },
  { name: 'Japan', dialCode: '81', code: 'JP', flag: '🇯🇵', minLength: 10, maxLength: 11 },
  { name: 'Jersey', dialCode: '44', code: 'JE', flag: '🇯🇪', minLength: 10, maxLength: 10 },
  { name: 'Jordan', dialCode: '962', code: 'JO', flag: '🇯🇴', minLength: 9, maxLength: 9 },
  { name: 'Kazakhstan', dialCode: '7', code: 'KZ', flag: '🇰🇿', minLength: 10, maxLength: 10 },
  { name: 'Kenya', dialCode: '254', code: 'KE', flag: '🇰🇪', minLength: 9, maxLength: 9 },
  { name: 'Kiribati', dialCode: '686', code: 'KI', flag: '🇰🇮', minLength: 5, maxLength: 5 },
  { name: 'Kuwait', dialCode: '965', code: 'KW', flag: '🇰🇼', minLength: 8, maxLength: 8 },
  { name: 'Kyrgyzstan', dialCode: '996', code: 'KG', flag: '🇰🇬', minLength: 9, maxLength: 9 },
  { name: 'Laos', dialCode: '856', code: 'LA', flag: '🇱🇦', minLength: 9, maxLength: 10 },
  { name: 'Latvia', dialCode: '371', code: 'LV', flag: '🇱🇻', minLength: 8, maxLength: 8 },
  { name: 'Lebanon', dialCode: '961', code: 'LB', flag: '🇱🇧', minLength: 8, maxLength: 8 },
  { name: 'Lesotho', dialCode: '266', code: 'LS', flag: '🇱🇸', minLength: 8, maxLength: 8 },
  { name: 'Liberia', dialCode: '231', code: 'LR', flag: '🇱🇷', minLength: 8, maxLength: 8 },
  { name: 'Libya', dialCode: '218', code: 'LY', flag: '🇱🇾', minLength: 9, maxLength: 9 },
  { name: 'Liechtenstein', dialCode: '423', code: 'LI', flag: '🇱🇮', minLength: 7, maxLength: 7 },
  { name: 'Lithuania', dialCode: '370', code: 'LT', flag: '🇱🇹', minLength: 8, maxLength: 8 },
  { name: 'Luxembourg', dialCode: '352', code: 'LU', flag: '🇱🇺', minLength: 9, maxLength: 9 },
  { name: 'Macau', dialCode: '853', code: 'MO', flag: '🇲🇴', minLength: 8, maxLength: 8 },
  { name: 'Madagascar', dialCode: '261', code: 'MG', flag: '🇲🇬', minLength: 9, maxLength: 9 },
  { name: 'Malawi', dialCode: '265', code: 'MW', flag: '🇲🇼', minLength: 9, maxLength: 9 },
  { name: 'Malaysia', dialCode: '60', code: 'MY', flag: '🇲🇾', minLength: 9, maxLength: 10 },
  { name: 'Maldives', dialCode: '960', code: 'MV', flag: '🇲🇻', minLength: 7, maxLength: 7 },
  { name: 'Mali', dialCode: '223', code: 'ML', flag: '🇲🇱', minLength: 8, maxLength: 8 },
  { name: 'Malta', dialCode: '356', code: 'MT', flag: '🇲🇹', minLength: 8, maxLength: 8 },
  { name: 'Marshall Islands', dialCode: '692', code: 'MH', flag: '🇲🇭', minLength: 7, maxLength: 7 },
  { name: 'Martinique', dialCode: '596', code: 'MQ', flag: '🇲🇶', minLength: 9, maxLength: 9 },
  { name: 'Mauritania', dialCode: '222', code: 'MR', flag: '🇲🇷', minLength: 8, maxLength: 8 },
  { name: 'Mauritius', dialCode: '230', code: 'MU', flag: '🇲🇺', minLength: 8, maxLength: 8 },
  { name: 'Mayotte', dialCode: '262', code: 'YT', flag: '🇾🇹', minLength: 9, maxLength: 9 },
  { name: 'Mexico', dialCode: '52', code: 'MX', flag: '🇲🇽', minLength: 10, maxLength: 10 },
  { name: 'Micronesia', dialCode: '691', code: 'FM', flag: '🇫🇲', minLength: 7, maxLength: 7 },
  { name: 'Moldova', dialCode: '373', code: 'MD', flag: '🇲🇩', minLength: 8, maxLength: 8 },
  { name: 'Monaco', dialCode: '377', code: 'MC', flag: '🇲🇨', minLength: 8, maxLength: 8 },
  { name: 'Mongolia', dialCode: '976', code: 'MN', flag: '🇲🇳', minLength: 8, maxLength: 8 },
  { name: 'Montenegro', dialCode: '382', code: 'ME', flag: '🇲🇪', minLength: 8, maxLength: 8 },
  { name: 'Montserrat', dialCode: '1664', code: 'MS', flag: '🇲🇸', minLength: 10, maxLength: 10 },
  { name: 'Morocco', dialCode: '212', code: 'MA', flag: '🇲🇦', minLength: 9, maxLength: 9 },
  { name: 'Mozambique', dialCode: '258', code: 'MZ', flag: '🇲🇿', minLength: 9, maxLength: 9 },
  { name: 'Myanmar', dialCode: '95', code: 'MM', flag: '🇲🇲', minLength: 9, maxLength: 10 },
  { name: 'Namibia', dialCode: '264', code: 'NA', flag: '🇳🇦', minLength: 9, maxLength: 9 },
  { name: 'Nauru', dialCode: '674', code: 'NR', flag: '🇳🇷', minLength: 7, maxLength: 7 },
  { name: 'Nepal', dialCode: '977', code: 'NP', flag: '🇳🇵', minLength: 8, maxLength: 10 },
  { name: 'Netherlands', dialCode: '31', code: 'NL', flag: '🇳🇱', minLength: 9, maxLength: 9 },
  { name: 'New Caledonia', dialCode: '687', code: 'NC', flag: '🇳🇨', minLength: 6, maxLength: 6 },
  { name: 'New Zealand', dialCode: '64', code: 'NZ', flag: '🇳🇿', minLength: 8, maxLength: 10 },
  { name: 'Nicaragua', dialCode: '505', code: 'NI', flag: '🇳🇮', minLength: 8, maxLength: 8 },
  { name: 'Niger', dialCode: '227', code: 'NE', flag: '🇳🇪', minLength: 8, maxLength: 8 },
  { name: 'Nigeria', dialCode: '234', code: 'NG', flag: '🇳🇬', minLength: 10, maxLength: 10 },
  { name: 'Niue', dialCode: '683', code: 'NU', flag: '🇳🇺', minLength: 4, maxLength: 4 },
  { name: 'Norfolk Island', dialCode: '672', code: 'NF', flag: '🇳🇫', minLength: 6, maxLength: 6 },
  { name: 'North Macedonia', dialCode: '389', code: 'MK', flag: '🇲🇰', minLength: 8, maxLength: 9 },
  { name: 'Northern Mariana Islands', dialCode: '1670', code: 'MP', flag: '🇲🇵', minLength: 10, maxLength: 10 },
  { name: 'Norway', dialCode: '47', code: 'NO', flag: '🇳🇴', minLength: 8, maxLength: 8 },
  { name: 'Oman', dialCode: '968', code: 'OM', flag: '🇴🇲', minLength: 8, maxLength: 8 },
  { name: 'Pakistan', dialCode: '92', code: 'PK', flag: '🇵🇰', minLength: 10, maxLength: 10 },
  { name: 'Palau', dialCode: '680', code: 'PW', flag: '🇵🇼', minLength: 7, maxLength: 7 },
  { name: 'Palestine', dialCode: '970', code: 'PS', flag: '🇵🇸', minLength: 9, maxLength: 9 },
  { name: 'Panama', dialCode: '507', code: 'PA', flag: '🇵🇦', minLength: 8, maxLength: 8 },
  { name: 'Papua New Guinea', dialCode: '675', code: 'PG', flag: '🇵🇬', minLength: 8, maxLength: 8 },
  { name: 'Paraguay', dialCode: '595', code: 'PY', flag: '🇵🇾', minLength: 9, maxLength: 9 },
  { name: 'Peru', dialCode: '51', code: 'PE', flag: '🇵🇪', minLength: 9, maxLength: 9 },
  { name: 'Philippines', dialCode: '63', code: 'PH', flag: '🇵🇭', minLength: 10, maxLength: 10 },
  { name: 'Poland', dialCode: '48', code: 'PL', flag: '🇵🇱', minLength: 9, maxLength: 9 },
  { name: 'Portugal', dialCode: '351', code: 'PT', flag: '🇵🇹', minLength: 9, maxLength: 9 },
  { name: 'Puerto Rico', dialCode: '1787', code: 'PR', flag: '🇵🇷', minLength: 10, maxLength: 10 },
  { name: 'Qatar', dialCode: '974', code: 'QA', flag: '🇶🇦', minLength: 8, maxLength: 8 },
  { name: 'Reunion', dialCode: '262', code: 'RE', flag: '🇷🇪', minLength: 9, maxLength: 9 },
  { name: 'Romania', dialCode: '40', code: 'RO', flag: '🇷🇴', minLength: 9, maxLength: 9 },
  { name: 'Russia', dialCode: '7', code: 'RU', flag: '🇷🇺', minLength: 10, maxLength: 10 },
  { name: 'Rwanda', dialCode: '250', code: 'RW', flag: '🇷🇼', minLength: 9, maxLength: 9 },
  { name: 'Saint Barthelemy', dialCode: '590', code: 'BL', flag: '🇧🇱', minLength: 9, maxLength: 9 },
  { name: 'Saint Helena', dialCode: '290', code: 'SH', flag: '🇸🇭', minLength: 4, maxLength: 4 },
  { name: 'Saint Kitts and Nevis', dialCode: '1869', code: 'KN', flag: '🇰🇳', minLength: 10, maxLength: 10 },
  { name: 'Saint Lucia', dialCode: '1758', code: 'LC', flag: '🇱🇨', minLength: 10, maxLength: 10 },
  { name: 'Saint Martin', dialCode: '590', code: 'MF', flag: '🇲🇫', minLength: 9, maxLength: 9 },
  { name: 'Saint Pierre and Miquelon', dialCode: '508', code: 'PM', flag: '🇵🇲', minLength: 6, maxLength: 6 },
  { name: 'Saint Vincent and the Grenadines', dialCode: '1784', code: 'VC', flag: '🇻🇨', minLength: 10, maxLength: 10 },
  { name: 'Samoa', dialCode: '685', code: 'WS', flag: '🇼🇸', minLength: 7, maxLength: 7 },
  { name: 'San Marino', dialCode: '378', code: 'SM', flag: '🇸🇲', minLength: 9, maxLength: 9 },
  { name: 'Sao Tome and Principe', dialCode: '239', code: 'ST', flag: '🇸🇹', minLength: 7, maxLength: 7 },
  { name: 'Saudi Arabia', dialCode: '966', code: 'SA', flag: '🇸🇦', minLength: 9, maxLength: 9 },
  { name: 'Senegal', dialCode: '221', code: 'SN', flag: '🇸🇳', minLength: 9, maxLength: 9 },
  { name: 'Serbia', dialCode: '381', code: 'RS', flag: '🇷🇸', minLength: 9, maxLength: 9 },
  { name: 'Seychelles', dialCode: '248', code: 'SC', flag: '🇸🇨', minLength: 7, maxLength: 7 },
  { name: 'Sierra Leone', dialCode: '232', code: 'SL', flag: '🇸🇱', minLength: 8, maxLength: 8 },
  { name: 'Singapore', dialCode: '65', code: 'SG', flag: '🇸🇬', minLength: 8, maxLength: 8 },
  { name: 'Sint Maarten', dialCode: '1721', code: 'SX', flag: '🇸🇽', minLength: 10, maxLength: 10 },
  { name: 'Slovakia', dialCode: '421', code: 'SK', flag: '🇸🇰', minLength: 9, maxLength: 9 },
  { name: 'Slovenia', dialCode: '386', code: 'SI', flag: '🇸🇮', minLength: 8, maxLength: 8 },
  { name: 'Solomon Islands', dialCode: '677', code: 'SB', flag: '🇸🇧', minLength: 7, maxLength: 7 },
  { name: 'Somalia', dialCode: '252', code: 'SO', flag: '🇸🇴', minLength: 9, maxLength: 9 },
  { name: 'South Africa', dialCode: '27', code: 'ZA', flag: '🇿🇦', minLength: 9, maxLength: 9 },
  { name: 'South Korea', dialCode: '82', code: 'KR', flag: '🇰🇷', minLength: 9, maxLength: 10 },
  { name: 'South Sudan', dialCode: '211', code: 'SS', flag: '🇸🇸', minLength: 9, maxLength: 9 },
  { name: 'Spain', dialCode: '34', code: 'ES', flag: '🇪🇸', minLength: 9, maxLength: 9 },
  { name: 'Sri Lanka', dialCode: '94', code: 'LK', flag: '🇱🇰', minLength: 9, maxLength: 9 },
  { name: 'Sudan', dialCode: '249', code: 'SD', flag: '🇸🇩', minLength: 9, maxLength: 9 },
  { name: 'Suriname', dialCode: '597', code: 'SR', flag: '🇸🇷', minLength: 7, maxLength: 7 },
  { name: 'Svalbard and Jan Mayen', dialCode: '47', code: 'SJ', flag: '🇸🇯', minLength: 8, maxLength: 8 },
  { name: 'Sweden', dialCode: '46', code: 'SE', flag: '🇸🇪', minLength: 9, maxLength: 10 },
  { name: 'Switzerland', dialCode: '41', code: 'CH', flag: '🇨🇭', minLength: 9, maxLength: 9 },
  { name: 'Syria', dialCode: '963', code: 'SY', flag: '🇸🇾', minLength: 9, maxLength: 9 },
  { name: 'Taiwan', dialCode: '886', code: 'TW', flag: '🇹🇼', minLength: 9, maxLength: 9 },
  { name: 'Tajikistan', dialCode: '992', code: 'TJ', flag: '🇹🇯', minLength: 9, maxLength: 9 },
  { name: 'Tanzania', dialCode: '255', code: 'TZ', flag: '🇹🇿', minLength: 9, maxLength: 9 },
  { name: 'Thailand', dialCode: '66', code: 'TH', flag: '🇹🇭', minLength: 9, maxLength: 9 },
  { name: 'Togo', dialCode: '228', code: 'TG', flag: '🇹🇬', minLength: 8, maxLength: 8 },
  { name: 'Tokelau', dialCode: '690', code: 'TK', flag: '🇹🇰', minLength: 4, maxLength: 4 },
  { name: 'Tonga', dialCode: '676', code: 'TO', flag: '🇹🇴', minLength: 7, maxLength: 7 },
  { name: 'Trinidad and Tobago', dialCode: '1868', code: 'TT', flag: '🇹🇹', minLength: 10, maxLength: 10 },
  { name: 'Tunisia', dialCode: '216', code: 'TN', flag: '🇹🇳', minLength: 8, maxLength: 8 },
  { name: 'Turkey', dialCode: '90', code: 'TR', flag: '🇹🇷', minLength: 10, maxLength: 10 },
  { name: 'Turkmenistan', dialCode: '993', code: 'TM', flag: '🇹🇲', minLength: 8, maxLength: 8 },
  { name: 'Turks and Caicos Islands', dialCode: '1649', code: 'TC', flag: '🇹🇨', minLength: 10, maxLength: 10 },
  { name: 'Tuvalu', dialCode: '688', code: 'TV', flag: '🇹🇻', minLength: 5, maxLength: 5 },
  { name: 'Uganda', dialCode: '256', code: 'UG', flag: '🇺🇬', minLength: 9, maxLength: 9 },
  { name: 'Ukraine', dialCode: '380', code: 'UA', flag: '🇺🇦', minLength: 9, maxLength: 9 },
  { name: 'United Arab Emirates', dialCode: '971', code: 'AE', flag: '🇦🇪', minLength: 9, maxLength: 9 },
  { name: 'United Kingdom', dialCode: '44', code: 'GB', flag: '🇬🇧', minLength: 10, maxLength: 11 },
  { name: 'United States', dialCode: '1', code: 'US', flag: '🇺🇸', minLength: 10, maxLength: 10 },
  { name: 'Uruguay', dialCode: '598', code: 'UY', flag: '🇺🇾', minLength: 8, maxLength: 8 },
  { name: 'Uzbekistan', dialCode: '998', code: 'UZ', flag: '🇺🇿', minLength: 9, maxLength: 9 },
  { name: 'Vanuatu', dialCode: '678', code: 'VU', flag: '🇻🇺', minLength: 7, maxLength: 7 },
  { name: 'Vatican City', dialCode: '379', code: 'VA', flag: '🇻🇦', minLength: 6, maxLength: 6 },
  { name: 'Venezuela', dialCode: '58', code: 'VE', flag: '🇻🇪', minLength: 10, maxLength: 10 },
  { name: 'Vietnam', dialCode: '84', code: 'VN', flag: '🇻🇳', minLength: 9, maxLength: 10 },
  { name: 'Wallis and Futuna', dialCode: '681', code: 'WF', flag: '🇼🇫', minLength: 6, maxLength: 6 },
  { name: 'Yemen', dialCode: '967', code: 'YE', flag: '🇾🇪', minLength: 9, maxLength: 9 },
  { name: 'Zambia', dialCode: '260', code: 'ZM', flag: '🇿🇲', minLength: 9, maxLength: 9 },
  { name: 'Zimbabwe', dialCode: '263', code: 'ZW', flag: '🇿🇼', minLength: 9, maxLength: 9 }
];
